### ISSUE TITLE
Extract data from IV.2.Importations_par_rubrique\ en\ valeur_19.xls file

### ISSUE THREAD

**Issue by lionel-k** [burundiarxiv/brb-open-data#1]
- [x] Extract only the monthly data
- [x] Export data as the sample in `csv/samples/importations-par-rubrique-en-valeur.csv`

**Comment by noryve-03** [comment]
Hey,
I created a scripts folder in which I want to put the scripts that I will be using for the project. The script that I put in the folder(test.py) is used to download files, extract the data, and export them to CSV. As you can see in the CSV folder, the downloaded file is automatically converted to CSV. So far, the script only works for the "Importations par rubrique en valeur" file and a couple of other files but I hope I will tweak it enough for it to work with all the data on the BRB website.  
I also want the script to run automatically using Github Actions. However, I have not implemented the functionality yet. I am still creating a draft of the GitHub actions, and I will add it to the repo later. If you can help me with that, and the Github workflow executes the script once a week, it would be tremendously helpful.
